"""chatstages table

Revision ID: fd79d071a9ec
Revises: 1c188cb562ae
Create Date: 2020-04-18 21:38:40.023616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd79d071a9ec'
down_revision = '1c188cb562ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_stage_estagio_usuario', table_name='chat_stage')
    op.create_index(op.f('ix_chat_stage_estagio_usuario'), 'chat_stage', ['estagio_usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_stage_estagio_usuario'), table_name='chat_stage')
    op.create_index('ix_chat_stage_estagio_usuario', 'chat_stage', ['estagio_usuario'], unique=False)
    # ### end Alembic commands ###
