"""chat_stage table

Revision ID: 3c6f4ce35c0b
Revises: 0e871e1321c1
Create Date: 2020-04-19 17:29:50.137428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6f4ce35c0b'
down_revision = '0e871e1321c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_stage', sa.Column('fluxo_de_dialogo', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_chat_stage_fluxo_de_dialogo'), 'chat_stage', ['fluxo_de_dialogo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_stage_fluxo_de_dialogo'), table_name='chat_stage')
    op.drop_column('chat_stage', 'fluxo_de_dialogo')
    # ### end Alembic commands ###
