"""users table

Revision ID: cf4799b27c71
Revises: 
Create Date: 2020-04-18 19:48:47.427772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4799b27c71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cpf', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cpf'), 'user', ['cpf'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('chat_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estagio_usuario', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_stage_estagio_usuario'), 'chat_stage', ['estagio_usuario'], unique=True)
    op.create_index(op.f('ix_chat_stage_timestamp'), 'chat_stage', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_stage_timestamp'), table_name='chat_stage')
    op.drop_index(op.f('ix_chat_stage_estagio_usuario'), table_name='chat_stage')
    op.drop_table('chat_stage')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_cpf'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
